# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-27 11:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.contrib.wagtailroutablepage.models
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailregulations', '__first__'),
        ('wagtailcore', '0040_page_draft_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestRegulationLandingPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('body', wagtail.wagtailcore.fields.StreamField((('title', wagtail.wagtailcore.blocks.CharBlock()), ('introduction', wagtail.wagtailcore.blocks.RichTextBlock()), ('regulations_list', wagtail.wagtailcore.blocks.StructBlock((('heading', wagtail.wagtailcore.blocks.CharBlock(help_text='Regulations list heading', required=False)), ('more_regs_page', wagtail.wagtailcore.blocks.PageChooserBlock(help_text='Link to more regulations')), ('more_regs_text', wagtail.wagtailcore.blocks.CharBlock(help_text='Text to show on link to more regulations', required=False)))))))),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtail.contrib.wagtailroutablepage.models.RoutablePageMixin, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='TestRegulationPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('body', wagtail.wagtailcore.fields.StreamField((('title', wagtail.wagtailcore.blocks.CharBlock()), ('introduction', wagtail.wagtailcore.blocks.RichTextBlock())))),
                ('regulation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='page', to='wagtailregulations.Part')),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtail.contrib.wagtailroutablepage.models.RoutablePageMixin, 'wagtailcore.page', models.Model),
        ),
    ]
