version: '2'

services:
  db:
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: changeme
    restart: always
    image: postgres:12.2
    expose:
      - "5432"
  app:
    environment:
      DJANGO_SECRET_KEY: changeme
      DATABASE_URL: postgres://app_user:changeme@db/app_db
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/code
    links:
      - db:db
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
  media-root:

